sonar.projectKey=LAB_PIPELINE_CICD
sonar.projectName=LAB_PIPELINE_CICD
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=reports/bandit-report.json
sonar.python.ruff.reportPaths=reports/ruff-report.json
sonar.sarifReportPaths=reports/trivy-report.sarif