name: Reusable Bandit

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          python -m pip install bandit

      - name: Run Bandit and save JSON report
        id: bandit
        run: |
          # Folder for reports that may later be sent to SonarQube.
          mkdir -p reports

          # Do not stop immediately if Bandit returns nonzero.
          # We want to save the report and upload it first.
          set +e

          # Example threshold:
          # -ll  => medium and high severity
          # -ii  => medium and high confidence
          python -m bandit \
            -r app/src \
            -f json \
            -o reports/bandit-report.json \
            -ll \
            -ii

          # Save Bandit's exit code as a step output.
          echo "exit_code=$?" >> "$GITHUB_OUTPUT"

          # Restore normal shell behavior.
          set -e

      - name: Upload Bandit report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: bandit-report
          path: reports/bandit-report.json

      - name: Fail if Bandit found issues
        if: steps.bandit.outputs.exit_code != '0'
        run: exit 1